services:
  # Backend Service
  - type: web
    name: urban-sentinel-backend
    runtime: docker
    rootDir: backend
    region: ohio
    plan: starter
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true

  # Frontend Service
  - type: web
    name: urban-sentinel-frontend
    runtime: static
    rootDir: frontend
    branch: main
    buildCommand: docker build --build-arg REACT_APP_API_URL=https://urban-sentinel-backend.onrender.com -t urban-sentinel-frontend . && docker run --rm urban-sentinel-frontend npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://urban-sentinel-backend.onrender.com
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 